import 'package:flutter/material.dart';

class AppStrings {
  AppStrings(this.locale);
  final Locale locale;
  static AppStrings of(BuildContext context) => AppStrings(Localizations.localeOf(context));
  bool get fa => locale.languageCode == 'fa';
  String get appTitle => fa ? 'آزمایشگر پروکسی تلگرام' : 'Telegram Proxy Tester';
  String get proxies => fa ? 'پروکسی‌ها' : 'Proxies';
  String get proxyList => fa ? 'فهرست پروکسی‌ها' : 'Proxy list';
  String get sources => fa ? 'منابع' : 'Sources';
  String get settings => fa ? 'تنظیمات' : 'Settings';
  String get refresh => fa ? 'به‌روزرسانی' : 'Refresh';
  String get noProxies => fa ? 'هنوز پروکسی‌ای ثبت نشده است.' : 'No proxies have been added yet.';
  String get noSources => fa ? 'هنوز منبعی ثبت نشده است.' : 'No sources have been added yet.';
  String get sourceDescription => fa ? 'منابع پیش‌فرض GitHub از ابتدا آماده هستند. می‌توانید منبع TXT یا مخزن دیگری اضافه کنید.' : 'Default GitHub sources are ready from the start. You can add another TXT file or repository.';
  String get notChecked => fa ? 'بررسی نشده' : 'Not checked';
  String get notValidated => fa ? 'اعتبارسنجی نشده' : 'Not validated';
  String get open => fa ? 'باز کردن' : 'Open';
  String get language => fa ? 'زبان' : 'Language';
  String get theme => fa ? 'تم' : 'Theme';
  String get system => fa ? 'سیستم' : 'System';
  String get persian => fa ? 'فارسی' : 'Persian';
  String get english => fa ? 'انگلیسی' : 'English';
  String get light => fa ? 'روشن' : 'Light';
  String get dark => fa ? 'تاریک' : 'Dark';
  String get retention => fa ? 'نگهداری داده‌ها' : 'Data retention';
  String get checkHistoryRetention => fa ? 'مدت نگهداری تاریخچه بررسی‌ها' : 'Proxy check history retention';
  String get staleProxyRetention => fa ? 'مدت حذف پروکسی بدون پاسخ موفق' : 'Stale proxy retention';
  String get days => fa ? 'روز' : 'days';
  String get addSource => fa ? 'افزودن منبع' : 'Add source';
  String get sourceUrl => fa ? 'لینک TXT یا مخزن GitHub' : 'TXT URL or GitHub repository';
  String get validateBeforeSave => fa ? 'اعتبارسنجی قبل از ذخیره' : 'Validate before saving';
  String get validationHint => fa ? 'در صورت قطعی شبکه می‌توانید آن را خاموش کنید.' : 'Disable this if the network is unavailable.';
  String get cancel => fa ? 'لغو' : 'Cancel';
  String get save => fa ? 'ذخیره' : 'Save';
  String get githubRepository => fa ? 'مخزن GitHub' : 'GitHub repository';
  String get txtFile => fa ? 'فایل TXT' : 'TXT file';
  String get pending => fa ? 'در انتظار به‌روزرسانی' : 'Pending update';
  String get synced => fa ? 'به‌روزرسانی شد' : 'Updated';
  String get syncFailed => fa ? 'به‌روزرسانی ناموفق' : 'Update failed';
  String get validationSkipped => fa ? 'اعتبارسنجی رد شد' : 'Validation skipped';
  String imported(int count) => fa ? '$count پروکسی وارد شد.' : '$count proxies imported.';
  String get search => fa ? 'جست‌وجوی دامنه یا IP' : 'Search domain or IP';
  String get healthyOnly => fa ? 'سالم' : 'Healthy';
  String get favorites => fa ? 'موردعلاقه' : 'Favorites';
  String get close => fa ? 'بستن' : 'Close';
  String get checkHealth => fa ? 'بررسی سلامت پروکسی‌ها' : 'Check proxy health';
  String healthResult(int count) => fa ? '$count پروکسی بررسی شد.' : '$count proxies checked.';
  String get cleanup => fa ? 'پاک‌سازی داده‌های قدیمی' : 'Clean up old data';
  String cleanupResult(int checks, int proxies) => fa ? '$checks نتیجه بررسی و $proxies پروکسی حذف شد.' : '$checks checks and $proxies proxies removed.';
}
